import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { FileUploader } from "../components/FileUploader";
import SpritesheetCanvas from "../components/SpritesheetCanvas";
import * as url from "../public/adventurer_sprite_sheet_v1.1.png";

const Home: NextPage = () => {
  const [selectedFile, setSelectedFile] = useState<any>(null);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FileUploader
        onFileSelect={(file) => {
          console.log(file);
          const objectURL = URL.createObjectURL(file);

          setSelectedFile(objectURL);
        }}
      />
      {selectedFile && <SpritesheetCanvas imgData={selectedFile} />}
    </div>
  );
};

export default Home;
